pipeline:
  name: custom pipeline
  identifier: custom_pipeline
  projectIdentifier: donotdeleteshivanand
  orgIdentifier: Harness_io
  tags: {}
  stages:
    - stage:
        name: test1
        identifier: test1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10s
        tags: {}
